#!/usr/bin/env bash

SUBJECT="$1"
SENDER=$(echo "$2" | sed 's/.*<//' | sed 's/>.*//')
PARAM=${SUBJECT:6}
ADMIN_EMAIL=fidian@rumkin.com
IS_ADMIN=false

if [[ "$SENDER" == "$ADMIN_EMAIL" ]]; then
    IS_ADMIN=true
fi

cat <<EOF
Debug Information - $(date)

$(uptime)

$(df -h)


EOF

if ! $IS_ADMIN; then
    echo "You're not an admin, so I am not showing mail logs."
else
    # Admin: Find logs matching a query
    echo "Recent Results For $PARAM"
    echo "------------------------------------------------------------------"
    echo ""
    grep --before-context=1 --after-context=4 "^    From:.*$PARAM" logs/procmail.log
    echo ""
    echo ""
    echo "Mail logs"
    echo "------------------------------------------------------------------"
    echo ""
    logs=(/var/log/mail.log.1 /var/log/mail.log)
    ids=()

    while read id; do
        ids[${#ids[@]}]=$id
    done < <(grep "$1" "${logs[@]}" | sed 's/.*: \([0-9A-F]*\): to=.*/\1/')

    if [[ "${#ids[@]}" -eq 0 ]]; then
        echo "No mail logs found."
    else
        for id in "${ids[@]}"; do
            grep -h "$id" "${logs[@]}"
            echo "-----"
        done
    fi
fi
