#!/bin/bash
#
# Pipe formmail headers into this
#
# Normally this runs in the fileserver folder

DIR="pdf_$$"
mkdir "$DIR"
cat | sed "/^$/d"
OUTPUT="$DIR/webpage.pdf"

# This must use the older version of xvfb-run that delays a fixed amount of
# time instead of waiting for SIGUSR1 because Xvfb doesn't apparently send
# SIGUSR1 when started from the forked procmail/fetchmail.  Couldn't
# figure it out.
../timeout 30 ../xvfb-run -a -s "-screen 0 1024x768x24" "wkhtmltopdf" "$1" "$OUTPUT" > "$DIR/stdout" 2> "$DIR/stderr"

if [[ -s "$OUTPUT" ]]; then
    mime-construct --output --type application/pdf --attachment webpage.pdf --file "$OUTPUT"
    echo ""
else
    echo ""
    cat pdf-timeout
fi

rm -rf "$DIR"
