#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Specify a from address as the argument"
    exit 1
fi

cd ~
procmail -f "$1" webpage/procmailrc <<EOF
To: webpage@rumkin.com
From: "Test User" <$1>
Subject: pdf http://rumkin.com

This is my body of the message
EOF
